#
###################################
# Site wide configuration
####################################
#
title:       Desert Ratz
short_name:  RATZ
motto:       Blaze a Trail, Leave No Sand Unturned
keywords:    desert, ratz, hll, hell let loose
locale:      en
baseurl:     ""
url:         https://desert-ratz.com
lang:        en
description: Desert Ratz are a hell let loose clan based in Europe

background_image:   /images/bg.png

#
###################################
# Socials
###################################
#
socials:
  discord:      https://discord.gg/desertratz
  #facebook:    desertratz
  #instagram:   desertratz
  #youtube:     desertratz
  #twitter:     desertratz
  #telegram:    desertratz

#
###################################
# PWA Settings
####################################
#
lang_direction:   "ltr"
color:            "#f07b05"
background_color: "#1a1919"

#
###################################
# Jekyll-SEO-tag settings
####################################
#
analytics-id: G-Q6YD5NSC1F


logo: /images/logo_843x885.png

settings:
  rating: general  # May be general, mature, restricted, 14 years or safe for kids

author: ratz

# Comments
#disqus_shortname:   flottastellare

#google-site-verification:




# personal
location:           Wong Sher
phone:              310-318-5555
email:              info@default.com # change this to your email to receive free emails for your contact submissions via Slapform.com
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

# Scopes
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      permalink: "/news/:title/"
      layout: post
      author:
      image: /images/logo_843x885.png

  -
    scope:
      path: ""
      type: events
    values:
      permalink: "/events/:category/"
      layout: event
      image: /images/logo_843x885.png

collections:
  posts:
    output: true
    permalink: /news/:title/

#
###################################
# Jekyll configuration
####################################
#
permalink:          /news/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jemoji

paginate: 6
paginate_path: "/news/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, external_sites, src, vendor, CNAME, LICENSE, Rakefile, old]
